### ISSUE TITLE
For every one user that logs in, 3 socket connections are made?

### ISSUE THREAD

**Issue by twintailsstudios** [twintailsstudios/tastytails.net#2]
Every time a new user connects, 3 different socket ids are created. Only one socket id actually gets assigned an avatar and is able to chat. The other two just sit, as if they are on the avatar selection screen, not actually picking a sprite. 

I can't figure out where in my code is causing 3 connections to be made for each individual user...

look @brandonvdongen I used the issue thingy! :D

**Comment by brandonvdongen** [comment]
looking into it, will also have a vacation in 2 weeks so will have more time to help out then :3

**Comment by twintailsstudios** [comment]
I fixed the issue! It turns out this was the reason why usernames weren't working properly either. But now there is only one socket connection per user!
